### ISSUE TITLE
[BUG] 썸네일 스니펫 생성 시 스니펫 검증 추가

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#156]
## 🐞 어떤 버그인가요?
> 썸네일 스니펫 생성 시, 템플릿와 스니펫을 저장합니다.
이때 요청하는 스니펫이 템플릿의 스니펫이 맞는지 검증이 필요합니다.

## 🙄 어떤 상황에서 발생한 버그인가요?
> 현재 배포된 서버의 데이터베이스에 해당 템플릿의 스니펫이 아니지만 대표 스니펫으로 되어버린 더미데이터가 남아있었습니다.ㅠ

## 🎁 예상 결과
> 템플릿 삭제 시 대표 스니펫, 템플릿, 스니펫들이 전체 정상 삭제되어야 합니다.

## ⏳ 예상 소요 시간
> 1시간

**Comment by kyum-q** [comment]
2차 데모데이 전날에 해결한 이슈입니다
