### ISSUE TITLE
[FEAT] 검색

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#187]
## 📌 어떤 기능인가요?
> 키워드에 맞는 템플릿 목록을 조회한다.

## 📜 작업 상세 내용
- [ ] 카테고리, 태그, 글 제목, 글 내용 중 키워드에 일치하는 템플릿 목록을 조회한다.

## ⏳ 예상 소요 시간
> 이슈를 완료하기까지 예상되는 소요 시간을 분 or 시간 or 일 단위로 작성해주세요.

**Comment by kyum-q** [comment]
동일한 이슈가 존재하므로 close #55
