### ISSUE TITLE
[REFACTOR] 롬복 업그레이드

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#202]
## 📌 어떤 기능을 리팩터링 하나요?
- 오래된 롬복 버전 업그레이드(현재 최신 1.18.34)
- 자동으로 최신버전을 사용하도록 변경

## AS-IS

```gradle
dependencies {
    compileOnly 'org.projectlombok:lombok:0.11.0'
}
```

## TO-BE
```gradle
dependencies {
    compileOnly 'org.projectlombok:lombok'
}
```

## ⏳ 예상 소요 시간
- 1시간 이내

**Comment by zangsu** [comment]
오, 버전을 명시하지 않으면 알아서 사전에 정의된 버전으로 의존성을 추가해 주나 보네요!
[SOF - How are some gradle dependencies working with no version supplied](https://stackoverflow.com/questions/41676534/how-are-some-gradle-dependencies-working-with-no-version-supplied)
Zzzeus 가 발행한 이슈 덕분에 새롭게 하나 배워 갑니다!!
+) 작업은 제우스가 스스로 할당하신 건가요? 아니라면, 제가 빠르게 작업해서 올려둘까요?

**Comment by zeus6768** [comment]
> 오, 버전을 명시하지 않으면 알아서 사전에 정의된 버전으로 의존성을 추가해 주나 보네요!
> 
> [SOF - How are some gradle dependencies working with no version supplied](https://stackoverflow.com/questions/41676534/how-are-some-gradle-dependencies-working-with-no-version-supplied)
> 
> Zzzeus 가 발행한 이슈 덕분에 새롭게 하나 배워 갑니다!!
> 
> +) 작업은 제우스가 스스로 할당하신 건가요? 아니라면, 제가 빠르게 작업해서 올려둘까요?

간단한 작업이라 누가 작업하든 좋을 것 같아요. 

짱수가 해준다면 고맙겠어요!
