### ISSUE TITLE
[BUG] DEV 환경 Request,Response 로깅 시 correlationId 가 안찍힘

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#420]
## 🐞 어떤 버그인가요?
> DEV 환경 Request,Response 로깅 시 correlationId 가 안 찍힙니다.
메서드 측정 로그에는 찍히지만 어떤 요청에 의해 실행된 메서드인지 확인할 수 없습니다.

## 🙄 어떤 상황에서 발생한 버그인가요?
> 로컬에서는 찍히나 개발 환경에서 찍히지 않아 요청 추적 시 어려움이 있습니다.

## 🎁 예상 결과
> Request,Response, MethodExecution 에 correlationId 함께 로깅

## ⏳ 예상 소요 시간
> 이슈를 완료하기까지 예상되는 소요 시간을 분 or 시간 or 일 단위로 작성해주세요.

**Comment by zeus6768** [comment]
<img width="506" alt="Screenshot 2024-08-21 at 2 14 23 PM" src="https://github.com/user-attachments/assets/ba0c8a36-ca56-4795-a2f9-4a7846cecb54">
