### ISSUE TITLE
[REFACTOR] QA 및 에러 처리

### ISSUE THREAD

**Issue by Hain-tain** [woowacourse-teams/2024-code-zap#581]
## 📌 어떤 기능을 리팩터링 하나요?
불특정 사용자 배포를 위해 중요한 QA 및 에러 처리

## AS-IS
- [x] 400 대 에러 발생 시 사용자에게 에러 정보를 전달하지 않고있음.
- [x] 소스코드 입력시 무한으로 글자 입력 가능
- [x] 랜딩페이지에서 로그인을 했는데 ‘로그인 하러 가기’가 있음
## TO-BE
- [x] 템플릿 생성 실패할 경우, 토스트로 실패하였다고 알림하기
- [x] 템플릿 생성 실패한 경우, 라우터 이동 없이 생성 화면단 유지하기 
- [x]  특정 길이 이상 입력 시 프론트 단에서 입력 아예 불가능하도록 막기
- [x] 로그인 한 사용자에게는 랜딩페에지에서 '로그인 하러 가기’, '회원가입하기' 버튼 안보이게 처리한다.

## ⏳ 예상 소요 시간
> 이슈를 완료하기까지 예상되는 소요 시간을 분 or 시간 or 일 단위로 작성해주세요.

**Comment by Hain-tain** [comment]
<img width="265" alt="image" src="https://github.com/user-attachments/assets/47c652e4-29ab-4db3-a72e-ee5380cbca2e">

파일명 및 소스코드 길이제한 참고하세요~

**Comment by jminkkk** [comment]
## 새 템플릿 창의 카테고리 설정 모달
##### 목록 확인
- "엔터로 등록해요" 창 글자 색이 또렷했으면 좋겠다.

#### 카테고리 선택
- 카테고리 선택 안했을 시, ‘카테고리’라는 자동 선택된다
	- 현재는 "카테고리"라는 카테고리를 생성할 수 있기 때문에 디폴트로 카테고리가 있다면 유저 입장에서 "카테고리"라는 카테고리가 있다고 생각할 수 있다.
	- 결론: "카테고리"라는 카테고리를 막자
