### ISSUE TITLE
[QA] 배포 전 체크리스트 작성

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#591]
# QA 목표
- 배포 전 필수적인 조치가 이루어져야 하는 결함 또는 개선사항 발견
- 피드백에 없었던 결함 발견

## 도메인 별 체크리스트 작성
- [x] 회원가입, 로그인 (제)
- [x] 템플릿, 소스코드 (헤몰월)
- [x] 카테고리, 태그 (켬초마)
- [x] 익스텐션 (짱)

**Comment by Hain-tain** [comment]
## 템플릿, 소스코드 QA LIST

### 템플릿 생성, 조회
- [ ] 템플릿 제목을 입력하지 않으면 생성되지 않는다.
- [ ] 파일명을 입력하지 않으면 생성되지 않는다.
- [ ] 소스코드를 입력하지 않으면 생성되지 않는다.
- [ ] 제목, 파일명, 소스코드만 입력하면 템플릿이 생성된다.
- [ ] 카테고리를 선택하면, 해당 카테고리로 템플릿이 생성된다.
- [ ] 설명을 입력하면, 템플릿 조회시 해당 설명을 확인할 수 있다.
- [ ] 태그를 작성하면, 템플릿 조회시 해당 태그를 확인할 수 있다.

### 템플릿 수정
- [ ] 템플릿 제목을 수정하면 수정된 제목으로 변경된다.
- [ ] 템플릿 제목을 모두 삭제하면 수정 사항을 저장할 수 없다.
- [ ] 템플릿 파일명을 수정하면 수정된 파일명으로 변경된다.
- [ ] 템플릿 소스코드를 변경하면 수정된 소스코드로 변경된다.
- [ ] 템플릿 소스코드를 추가하면 소스코드의 개수가 늘어난다.
- [ ] 템플릿 소스코드를 삭제하면 소스코드의 개수가 줄어든다.
- [ ] 템플릿 소스코드를 모두 삭제하면 수정 사항을 저장할 수 없다.
- [ ] 템플릿 파일명을 하나라도 입력하지 않으면 수정 사항을 저장할 수 없다.
- [ ] 템플릿 설명을 수정하면 수정된 제목으로 변경된다.
- [ ] 템플릿 설명을 모두 삭제해도 수정 사항을 저장할 수 있다.

### 템플릿 삭제
- [ ] 템플릿 삭제 버튼을 누르면 삭제 확인 모달이 뜬다.
    - [ ] 삭제 확인 모달에서 취소 버튼을 누르면, 템플릿이 삭제되지 않는다.
    - [ ] 삭제 확인 모달에서 삭제 버튼을 누르면, 템플릿이 삭제되고 내탬플릿 화면으로 이동한다.

### 템플릿 선택 삭제
- [ ] 템플릿 선택 삭제 버튼을 누르면, 템플릿 목록 수정 모드가 된다. (목록들이 반투명해진다.)
- [ ] 템플릿 목록 수정 모드에서 돌아가기 또는 취소하기 버튼을 누르면, 원래 목록 상태로 돌아간다.
- [ ] 템플릿 목록 수정 모드에서 일부 템플릿을 선택하고 삭제하기 버튼을 누르면 삭제 확인 모달이 뜬다.
    - [ ] 삭제 확인 모달에서 취소 버튼을 누르면, 템플릿들이 삭제되지 않는다.
    - [ ] 삭제 확인 모달에서 삭제 버튼을 누르면, 템플릿들이 삭제된다.
- [ ] 템플릿 목록 수정 모드에서 전체선택 버튼을 누르면, 전체(해당 목록 20개)가 선택된다.
- [ ] 전체 선택된 상황에서 전체 해제 버튼을 누르면, 하나도 선택되지 않은 상태가 된다.
- [ ] 전체 선택된 상황에서 하나라도 해제하면 전체 해제 버튼이 전체 선택 버튼으로 변경된다.

### 템플릿 목록 조회 
- [ ] 템플릿 목록을 조회할 수 있다. (템플릿 목록은 기본적으로 최신순으로 정렬된다.)
- [ ] 정렬 옵션에서 '오래된 순'을 선택하면 템플릿 목록이 오래된 순으로 정렬된다. 
- [ ] 카테고리를 선택하면 해당 카테고리에 속한 템플릿만 조회된다. 
- [ ] 템플릿 목록에서 페이지네이션을 통해 다음 페이지로 이동할 수 있다. 

### 템플릿 검색
- [ ] 검색어를 입력하면 해당 검색어에 맞는 템플릿이 조회된다.
- [ ] 검색 결과가 없으면 '검색 결과가 없습니다' 메시지가 표시된다.
- [ ] 카테고리를 선택하면 해당 카테고리 내에서만 검색된다.
- [ ] 태그를 선택하면 해당 태그에 맞는 템플릿이 필터링된다.
- [ ] 검색 결과는 최신순으로 정렬된다.
- [ ] 검색 결과에서 정렬 기준을 변경하면 선택한 기준에 따라 결과가 정렬된다.
- [ ] 여러 개의 필터(카테고리, 태그 등)를 적용하면 해당 조건에 맞는 템플릿이 조회된다.
- [ ] 검색어를 삭제하면 검색 결과가 초기화된다.

**Comment by vi-wolhwa** [comment]
## 템플릿 생성/수정
- [ ] 템플릿 제목의 길이는 255자를 초과할 수 없다.
- [ ] 파일명의 길이는 255자를 초과할 수 없다.
- [ ] 소스코드는 65,535 byte를 초과할 수 없다.
- [ ] 태그명은 30자를 초과할 수 없다.
- [ ] 템플릿 생성 중 실패해도 다른 페이지로 이동하지 않는다.
- [ ] 템플릿 제목, 파일명, 소스코드, 태그명을 최대 글자로 입력하였을 때, 템플릿이 정상적으로 생성되어야 한다.

## 템플릿 조회
- [ ] 템플릿 제목, 파일명, 소스코드, 태그명을 최대 글자로 입력하였을 때, 레이아웃이 변경되지 않아야 한다.

**Comment by zeus6768** [comment]
## 회원가입

### 1. 아이디 입력칸 하단 형식 경고 메시지

> 1자 이상의 아이디를 입력해주세요.
> 
- [ ]  아이디가 형식에 맞지 않는 경우 입력칸 하단에 적절한 메시지를 출력한다.
    - 형식: 영어, 한글 또는 숫자로 구성된 1~255자 길이의 문자열

### 2. 비밀번호 입력

> 영문자, 숫자를 포함한 8자 이상의 비밀번호를 입력해주세요.
> 
- [ ]  비밀번호가 형식에 맞지 않는 경우 입력칸 하단에 적절한 메시지를 출력한다.
    - 형식: 영어와 숫자를 포함한 8~16자 길이의 문자열
- [ ]  비밀번호 입력 칸의 값을 숨기거나 숨김을 해제할 수 있다.

### 3. 비밀번호 확인

> 비밀번호가 일치하지 않습니다.
> 
- [ ]  비밀번호가 일치하지 않는 경우 입력칸 하단에 적절한 메시지를 출력한다.
- [ ]  비밀번호 확인 입력 칸의 값을 숨기거나 숨김을 해제할 수 있다.

### 4. 회원가입

- [ ]  아이디, 비밀번호, 비밀번호 확인 입력 후 회원가입한다.

## 로그인

- [ ]  회원가입 시 입력한 아이디와 비밀번호를 입력 후 로그인한다.

**Comment by kyum-q** [comment]
# 카테고리, 태그 QA 목록

## - 카테고리

### 새 템플릿 업로드 페이지에서

##### 목록 확인
- [ ]  해당 회원의 기존 카테고리 목록을 확인할 수 있다

##### 카테고리 선택
- [ ]  카테고리 선택 안했을 시, ‘카테고리 없음’으로 자동 선택된다
- [ ]  원하는 카테고리를 선택할 수 있다

##### 카테고리 생성
- [ ]  새로운 카테고리 생성할 수 있다
- [ ]  새 카테고리 생성 시 생성한 카테고리로 자동 선택된다
- [ ]  카테고리 입력 시, 14자를 입력할 수 있다
- [ ]  카테고리 입력 시, 0자 입력 후 생성되지 않는다
- [ ]  카테고리 입력 시, 15자를 초과하면 입력되지 않는다
- [ ]  카테고리 생성에 실패하면 실패 가이드 메시지가 뜨고, 생성 요청이 보내지지 않는다.
- [ ]  같은 아이디로 창을 2개 띄웠을 때도 중복 생성이 되지 않는다

### 내 템플릿 페이지에서 카테고리 편집 모달

##### 목록 확인
- [ ]  해당 회원의 기존 카테고리 목록을 확인할 수 있다.
- [ ]  원하는 카테고리를 선택하면 해당되는 템플릿만 조회된다.
- [ ]  전체보기 카테고리에서는 모든 템플릿을 조회할 수 있다.

##### 카테고리 생성
- [ ]  새로운 카테고리 생성이 된다
- [ ]  카테고리 입력 시, 14자를 입력할 수 있다
- [ ]  카테고리 입력 시, 15자를 초과하면 입력되지 않는다
- [ ]  카테고리에 이미 1이 존재할 경우, 편집 창에서 1을 2로 수정하고 1이라는 카테고리 생성 가능하다.
- [ ]  카테고리에 이미 존재하는 이름의 카테고리를 생성할 수 없다
- [ ]  이미 존재하는 카테고리 생성 시 빨간색 선으로 동일한 카테고리를 알려준다

##### 카테고리 삭제
- [ ]  카테고리 삭제 버튼을 누르고 저장 버튼을 누르면 삭제된다
- [ ]  카테고리 삭제 버튼을 누르고 취소 버튼을 누르면 삭제되지 않는다

##### 카테고리 수정
- [ ]  카테고리를 수정 버튼을 누르고 카테고리 명을 수정할 수 있다.
- [ ]  카테고리 수정 후 저장 버튼을 누르면 수정된 값으로 저장된다.
- [ ]  카테고리 수정 후 취소 버튼을 누르면 수정되지 않는다.

##### 동작 문제 점검
- [ ]  카테고리 선택 후, 템플릿 상세 조회 후, 뒤로 가기
- [ ]  창 2개 띄우고, 한 카테고리를 수정하고, 다른 창에서 해당 카테고리를 삭제할 때 확인
- [ ]  창 2개 띄우고, 한 카테고리를 생성하고, 다른 창에서 해당 카테고리를 다시 한 번 생성하는 경우 에러가 발생한다.

## - 태그

### 템플릿 생성 및 수정 페이지에서

#### 태그 생성
    - [ ]  태그 창에 한글 입력 가능
    - [ ]  태그 창에 한글 입력 가능
    - [ ]  태그 창에 한글 입력 가능
    - [ ]  태그 창에 이모지 입력 가능
    - [ ]  띄어쓰기 시 태그 등록
    - [ ]  엔터 시 태그 등록
    - [ ]  태그 글자 수 1자 등록 가능
    - [ ]  태그 글자 수 30자 등록 가능
    - [ ]  태그 글자 수 0자 등록 불가능
    - [ ]  태그 글자 수 31자 등록 불가능
    - [ ]  태그 글자 수 30자 넘을 시 알림창 생성
    - [ ]  알림창 생성 무시하고 계속 입력했을 때 문제 없는지 파악
    - [ ]  태그 개수 제한 확인
    - [ ]  태그 선택했다 해제했을 때 동작 확인
        - 현재는 선택하면 맨 앞으로 가고, 해제하면 그 위치 그대로 남는 걸로 알고 있음. 해당 부분에 대한 논의 필요
    - [ ]  

#### 태그 삭제
    - [ ]  태그 하나 생성 수 input 창에서 백스페이스 동작 시 태그 동작 없음
    - [ ]  태그 x 버튼 클릭 시 삭제
    - [ ]  태그 컴포넌트 클릭 시 삭제

**Comment by zangsu** [comment]
## 크롬 익스텐션

- [ ] 로그인
	- [ ] 사용자 정보가 일치하지 않으면 오류 메시지
	- [ ] 올바른 정보로 로그인 성공
- [ ] 드래그 후 extension 으로 저장했을 때 
	- [ ] 저장한 모든 내용이 코드로 잘 저장이 된다.
	- [ ] 너무 긴 파일을 저장하면 오류
	- [ ] 제목이 너무 길면 오류
	- [ ] 파일 제목이 너무 길면 오류
- [ ] 편집하고 다시 나가면
	- [ ] 제목, 카테고리, 파일 이름, 파일 내용이 모두 유지가 된다.
- [ ] 로그인을 하지 않은 상태로 extension 을 사용하면 로그인 하라는 알림

+) 추가적인 의문점
- [ ] 카테고리 생성은 안되나 보네
- [ ] 카테고리를 선택하지 않으면 선택하라는 알림이 온다.
	- [ ] 이거 항목 다 별도로 되었으면 좋겠다.
- [ ] 소스파일 업로드 하면 알림
- [ ] 소스코드가 줄바꿈이 안되는듯???

**Comment by Hain-tain** [comment]
태그 QA 끝! 
논의사항 : 
- 한 쳄플릿 당 태그 개수 제한 둘 것인가? 
- 템플릿 목록에 있는 태그 필터에서 보이는 태그 개수 제한 둘 것인가?

**Comment by kyum-q** [comment]
원하는 QA

- [ ] 선택 삭제에서 템플릿을 선택하지 않았을 경우 돌아가기와 취소하기 둘 중 하나만 보여도 좋을 것 같아요 or 취소하기라는 선택지는 없애고 돌아가기만 남겨놔도 좋을 것 같아요 ~!

**Comment by jminkkk** [comment]
## 새 템플릿 창의 카테고리 설정 모달
##### 목록 확인
- "엔터로 등록해요" 창 글자 색이 또렷했으면 좋겠다.

#### 카테고리 선택
- 카테고리 선택 안했을 시, ‘카테고리’라는 자동 선택된다
	- 현재는 "카테고리"라는 카테고리를 생성할 수 있기 때문에 디폴트로 카테고리가 있다면 유저 입장에서 "카테고리"라는 카테고리가 있다고 생각할 수 있다.
	- 결론: "카테고리"라는 카테고리를 생성을 막던가 "카테고리 없음"이 디폴트여야 한다~

**Comment by kyum-q** [comment]
템플릿 전체 선택 문제

1. 전체보기에서 템플릿 전체 선택
2. 다른 카테고리로 이동 (전체 선택 메시지 이상해짐)

**Comment by zangsu** [comment]
## 회원가입

> 아이디가 형식에 맞지 않는 경우 입력칸 하단에 적절한 메시지를 출력한다.
 >   - 형식: 영어, 한글 또는 숫자로 구성된 1~255자 길이의 문자열

- 특수문자 (`-`, `_`) 가 들어가는 경우 경고 메시지를 출력하지 않음
	- 근데 저장은 됩니다. 특수 문자를 막거나, 경고 문구를 수정하면 좋을 것 같아요

- 1 자 이상의 글자를 입력했음에도 "1자 이상의 글자를 입력해 주세요" 라는 메시지가 나온다.
  - 글자 사이에 완성되지 않은 글자가 들어가는 경우 
  - `_`, `-` 이외의 나머지 특수문자 입력시

- 255자보다 긴 문자열을 입력해도 경고 문구가 나오지 않는다. 
	- 입력 예시 : `오집략잉옥묵취토득린굳걱빼굴첩떻션탑삼건련생책풀칼욧흘솝푼갚론펍찐좆먕깎험낚런썽좡통묘빛찍둘둥역낱헐훈밤푱삐벙늘울긍욱힛땀렀철뱀젤눅촉픔걍숨떡쪼륵겉믐뱃죌흑씀컫벼쬐흙쪘훗칩냔펄뭉욤슭견쨘끗슥찡곬짤쭉줌퍽뻑렁씐짱윽솜쫑룩빚뽕솨쿼떼땐훅짧뽀굄쿵빡쮸캭짤쑨횡띠쫀듕섣격격격쁠쁨짖쏠쑤퉁격오집략잉옥묵취토득린굳걱빼굴첩떻션탑삼건련생책풀칼욧흘솝푼갚론펍찐좆먕깎험낚런썽좡통묘빛찍둘둥역낱헐훈밤푱삐벙늘울긍욱힛땀렀철뱀젤눅촉픔걍숨떡쪼륵겉믐뱃죌흑씀컫벼쬐흙쪘훗칩냔펄뭉욤슭견쨘끗슥찡곬짤쭉줌퍽뻑렁씐짱윽솜쫑룩빚뽕솨쿼떼땐훅짧뽀굄쿵빡쮸캭짤쑨횡띠쫀듕섣격격격쁠쁨짖쏠쑤퉁격코오집략잉옥묵취토득린굳걱빼굴첩떻션탑삼건련생책풀칼욧흘솝푼갚론펍찐좆먕깎험낚런썽좡통묘빛찍둘둥역낱헐훈밤푱삐벙늘울긍욱힛땀렀철뱀젤눅촉픔걍숨떡쪼륵겉믐뱃죌흑씀컫벼쬐흙쪘훗칩냔펄뭉욤슭견쨘끗슥찡곬짤쭉줌퍽뻑렁씐짱윽솜쫑룩빚뽕솨쿼떼땐훅짧뽀굄쿵빡쮸캭짤쑨횡띠쫀듕섣격격격쁠쁨짖쏠쑤퉁격오집략잉옥묵취토득린굳걱빼굴첩떻션탑삼건련생책풀칼욧흘솝푼갚론펍찐좆먕깎험낚런썽좡통묘빛찍둘둥역낱헐훈밤푱삐벙늘울긍욱힛땀렀철뱀젤눅촉픔걍숨떡쪼륵겉믐뱃죌흑씀컫벼쬐흙쪘훗칩냔펄뭉욤슭견쨘끗슥찡곬짤쭉줌퍽뻑렁씐짱윽솜쫑룩빚뽕솨쿼떼땐훅짧뽀굄쿵빡쮸캭짤쑨횡띠쫀듕섣격격격쁠쁨짖쏠쑤퉁격코` -> 562자
	- 이대로 회원가입 진행시 응답은 400이 오지만 화면은 성공한 것 처럼 보인다.

 
> 비밀번호가 형식에 맞지 않는 경우 입력칸 하단에 적절한 메시지를 출력한다.
   > - 형식: 영어와 숫자를 포함한 8~16자 길이의 문자열
   
- 비밀번호의 최대 범위를 명시해 주지 않고 있다. 
	- 16자 이상을 입력하면 8자 이상으로 입력해 달라고 나온다.

+) 한글을 입력한 경우, CapsLock 이 눌린 경우 좀 더 가이드를 해 주면 더더 좋을텐데~

## 로그인

> 아이디 형식이 올바르지 않을 경우 입력칸 하단에 적절한 메시지를 출력한다.

- 최대 길이 명시 X

> 비밀번호 형식이 올바르지 않을 경우 입력칸 하단에 적절한 메시지를 출력한다.

- 최대 길이 명시 X

>[!check]   아이디 또는 비밀번호 형식이 올바르지 않을 경우 로그인 버튼이 비활성화된다.

- 아이디가 너무 길어도 로그인 버튼이 활성화 되어 있다.

**Comment by kyum-q** [comment]
선택 삭제 시 없는 카테고리로 가면 "~ 템플릿 추가해보세요" 라는 안내 문구가 어색하다
삭제하고 있는데 추가하라는 안내 메시지가 나오네 느낌
![image](https://github.com/user-attachments/assets/3fe2010b-bbd8-4f3e-8ff0-82644b49c3a6)

**Comment by vi-wolhwa** [comment]
### 템플릿 생성
- 템플릿 제목 글자수 제한

**Comment by jminkkk** [comment]
## 카테고리
카테고리 여러개 한번에 생성하고 카테고리 목록 조회 시 시간 순 정렬이 아니다

**Comment by HoeSeong123** [comment]
태그를 선택하면 맨 앞으로 가고, 해제하면 그 위치 그대로 남는 걸로 알고 있음. 해당 부분에 대한 논의 필요
