### ISSUE TITLE
[DOCS] 레벨4 VoC 목록

### ISSUE THREAD

**Issue by zeus6768** [woowacourse-teams/2024-code-zap#642]

**Comment by Hain-tain** [comment]
인기순 있으면 좋겠어요~
언어, 라이브리러(리액트)별 태깅 기능 있으면 좋겠어요~
그리고 로그인 해주세요 토스트가 좀 늦게 뜨는 것 같음
From. 6기 FE 해리

**Comment by zangsu** [comment]
![image](https://github.com/user-attachments/assets/147756a9-e0cf-40b9-a90e-8fa056940e43)

**Comment by HoeSeong123** [comment]
기존에 비밀번호를 16자 이상으로 회원가입을 했던 유저들이 로그인을 못하고 있습니다..

**Comment by zangsu** [comment]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/3fa8b666-116c-4fae-8c26-0bb291d0cbf8">

**Comment by Hain-tain** [comment]
- [ ] 코드잽이라고 검색했을 때 나오는 블로그가 안들어가짐
- [x] 선택 삭제에서 삭제하기 버튼을 누르면 텍스트 줄바꿈이 너무 불편함 
- [ ] 정렬 조건 바꿨을 때 1번 페이지로 가야할 것 같다.
- [ ] 페이지 변경 후 상세조회 -> 뒤로가기 했을 때 1번 페이지로 감
- [ ] 정렬 조건 바꾸고 상세조회 -> 뒤로가기 했을 때 1번 페이지로 감
- [ ] 코드 너비가 너무 좁은 것 같다. 특히 큰 모니터로 보는 경우 진짜 좁아보임

**Comment by Jaymyong66** [comment]
- [ ] 모바일 헤더 메뉴가 항상 닫힌다
- [ ] 간헐적으로 카테고리 ID가 들어가지 않는다
