### ISSUE TITLE
[REFACTOR] 서비스 테스트

### ISSUE THREAD

**Issue by kyum-q** [woowacourse-teams/2024-code-zap#645]
## 📌 어떤 기능을 리팩터링 하나요?
> 관련 디스커션 : https://github.com/woowacourse-teams/2024-code-zap/discussions/633
서비스들을 테스트한다.

##### @HoeSeong123 
- #661 
- #662 

##### @jminkkk  
- #663 
- #660  
- #653  

##### @zangsu 
- #657
- #656 
- #658 

##### @kyum-q 
- #654  
- #655 
- #646  

##### @zeus6768 
- #665 
- #666 

## ⏳ 예상 소요 시간
9/19

> - 수요일까지(9/18) 오후 6시까지 PR 코드리뷰 요청 마감
> - 목요일까지(9/19) 오후 6시까지 PR 머지

**Comment by zangsu** [comment]
`AuthService` 에 필요한 테스트가 모두 작성되어 있어 PR 을 따로 생성하지 않은 채 해결 표시 해 두었습니다~
