### ISSUE TITLE
[FEAT] Private 기능 구현

### ISSUE THREAD

**Issue by kyum-q** [woowacourse-teams/2024-code-zap#739]
## 📌 어떤 기능인가요?

> 템플릿 저장 시 템플릿 공개 여부를 설정할 수 있다.

## 🤔 기능 추가 이유

VoC와 내부 회의를 통해 지속적으로 **템플릿을 비공개하기**에 대한 수요를 확인

## 💎 최종 API 변경 및 정책
GET `/templates` 요청 시

- memberId를 param으로 주지 않으면 공개된 템플릿만 조회할 수 있다
- memberId를 param으로 준다면, 쿠키 정보를 통해 현재 로그인된 회원의 비공개 템플릿까지 포함되어 조회할 수 있다.

POST `/tempates/{id}`, POST `/templates` 요청 시

- visibility 추가

## 📜 작업 상세 내용

- [x] 템플릿 저장 시 공개 여부 선택 UI
- [x] 템플릿 swagger 문서화
- [x] 템플릿 생성 시, 공개 여부 포함하도록 body 변경
- [x] 템플릿 조회 시, memberId가 없으면 public 템플릿만 반환
- 템플릿 조회 시, memberId가 있으면
    - [x] memberId와 현재 쿠키 정보가 동일할 경우 private 템플릿까지 반환
    - [x] 동일하지 않으면 public 템플릿만 반환
- [x] 템플릿 수정 시, 공개 여부 포함하도록 body 변경

## ⏳ 예상 소요 시간
10/16 까지 1차 PR 제출

**Comment by kyum-q** [comment]
## API 변경

### 1차 API

GET `/templates` 

- isPrivate를 param으로 주면 비공개 템플릿을 함께 조회한다
  - 그러면 로그인 정보와 비교 해서 동일하면 private 템플릿도 제공한다.

### 2차 API

isPrivate를 받는 대신 memberId를 param으로 받을 때가 다른 사용자 혹은 내 템플릿 목록을 확인하는 시점이니 다음과 같이 수정하였다.
- memberId를 param으로 주지 않으면 공개된 템플릿만 조회할 수 있다
- memberId를 param으로 준다면, 쿠키 정보를 통해 현재 로그인된 회원의 비공개 템플릿까지 포함되어 조회할 수 있다.

**Comment by kyum-q** [comment]
## 디자인 변경

### 1차 디자인

 > visibility 선택 UI

https://github.com/user-attachments/assets/ef454086-0016-451c-a439-62dca595f7a8

 

### 2차 디자인

두가지 피드백을 받아 아래와 같이 수정하였다.

- 피드백
   - 공개 범위 선택 토글 위치가 제목 위치에 있으면 더 적절할 것 같다
   - 토글 색상이 너무 눈을 사로잡는다. 색상을 죽이면 더 좋을 것 같다

https://github.com/user-attachments/assets/ef454086-0016-451c-a439-62dca595f7a8

**Comment by Hain-tain** [comment]
## 디자인 변경

### 1차 디자인

 > visibility 선택 UI

https://github.com/user-attachments/assets/ef454086-0016-451c-a439-62dca595f7a8

 

### 2차 디자인 (최종)

두가지 피드백을 받아 아래와 같이 수정하였다.

- 피드백
   - 공개 범위 선택 토글 위치가 제목 위치에 있으면 더 적절할 것 같다
   - 토글 색상이 너무 눈을 사로잡는다. 색상을 죽이면 더 좋을 것 같다

https://github.com/user-attachments/assets/730acb33-9a23-47e2-bbc5-14ef84a6f283

**Comment by kyum-q** [comment]
## 페어프로그래밍 😜

![image](https://github.com/user-attachments/assets/c5b89ea2-42b5-4db7-8b93-84aa0fc5d283)
