### ISSUE TITLE
[REFACTOR] 로그백 파일 롤링 정책 변경

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#763]
## 📌 어떤 기능을 리팩터링 하나요?
> 현재 로그백 설정을 보면 SizeAndTimeBasedRollingPolicy로 적용이 되어 있습니다.

SizeAndTimeBasedRollingPolicy는 로그 파일이 특정 크기에 도달하면 새 파일을 생성합니다.
또한 시간(일반적으로 일 단위)에 따라 새 파일을 생성합니다.
현재 문제는 날짜가 변경되어도 크기가 특정 크기를 넘지 않으면 이전 날짜의 파일에 저장됩니다.

처음 찾아봤을 때는 Size과 Time이 동시에 반영된다고 해서 사용을 했는데, 명확한 설명을 못찾겠네요.

<img width="806" alt="image" src="https://github.com/user-attachments/assets/02871b28-6611-452f-8ef2-61b0aa32cc55">

트리거 조건도 시간이랑 크기 둘 중 하나라도 넘으면 안됨 
심지어 시간 먼저 검사함

### 제가 추측하는 문제 원인

1. SizeAndTimeBasedRollingPolicy가 Size 먼저 검사하고 Time 검사
2. Logback의 Time과 Spring의 Time이 달라서 Spring의 타임존을 서울로 설정해줘도 Logback은 적용이 안됨

그런데 2번은 스프링 애플리케이션 전체에 타임존을 적용했기 때문에 시간이 다르진 않을 것 같습니다..

아무튼 정책의 문제가 아닐 수도 있지만, 또 문제일 수도 있기 때문에 Time 기반으로만 적용될 수 있도록 변경합니다.
~~(다른 이슈 때문이지만 또 SizeAndTimeBasedRollingPolicy는 공식 문서에서도 그닥 추천하지 않더라구요)~~

변경했는데도 여전히 그러면 로그백 시간을 명시적으로 줘봐야할듯합니다.

## AS-IS
```
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
```

## TO-BE
```
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
```

## ⏳ 예상 소요 시간
> 3분

**Comment by zeus6768** [comment]
https://logback.qos.ch/manual/appenders.html#tbrpTotalSizeCap

TimeBasedRollingPolicy의 totalSizeCap 설정을 하면 시간 + 용량으로 우리가 원하는 조건을 걸 수 있다고 하네요. 

그렇게 해보면 어떨까요~!

**Comment by zangsu** [comment]
옹, 그런데 우리가 매일매일 로그를 확인하는 것이 아니라서 각 날짜마다 용량을 넘겼을때 삭제가 된다면 문제가 생길 수 있을 것 같기도 해요.
`SizeAndTimeBasedRollingPolicy` 은 용량이 넘어가면 새로운 파일로 넘어가서 작성을 하는 것 같더라구용
`totalSizeCap` 을 충분히 넉넉하게 설정하지 않는다면 오히려 걱정이 됩니닷,,,

**Comment by zeus6768** [comment]
> 옹, 그런데 우리가 매일매일 로그를 확인하는 것이 아니라서 각 날짜마다 용량을 넘겼을때 삭제가 된다면 문제가 생길 수 있을 것 같기도 해요.
> 
> `SizeAndTimeBasedRollingPolicy` 은 용량이 넘어가면 새로운 파일로 넘어가서 작성을 하는 것 같더라구용
> 
> `totalSizeCap` 을 충분히 넉넉하게 설정하지 않는다면 오히려 걱정이 됩니닷,,,

좋은 지적이네요~!

짱수의 코멘트를 보고 위 링크의 공식문서를 다시 읽어 봤는데, totalSizeCap이 전체 로그 파일의 용량을 의미하네요. 적절한 값으로 조정할 필요가 있겠어요~~👍
