### ISSUE TITLE
[BUG] docker-container 내 볼륨 설정된 파일이 자동으로 수정되지 않는 문제

### ISSUE THREAD

**Issue by kyum-q** [woowacourse-teams/2024-code-zap#881]
## 🐞 어떤 상황에서 발생한 버그인가요?

때때로 docker-container 내 볼륨 설정된 파일이 자동으로 수정되지 않는 문제가 있다.

## 🎁 예상 결과
host에 값을 변경했을 때 docker-container 내에 볼륨 설정된 파일이 함께 수정된다.

## ⏳ 예상 소요 시간 (예상 해결 날짜)
> 이슈를 완료하기까지 예상되는 소요 시간을 시간 or 일 단위로 작성해주세요. 

3일 0시간 소요 (00/00 00:00 : 아직 시작 안함)

**Comment by zeus6768** [comment]
nginx 설정을 submodule에서 분리함으로써 해결했습니다.
