### ISSUE TITLE
[REFACTOR] AWS 서버 마이그레이션

### ISSUE THREAD

**Issue by jminkkk** [woowacourse-teams/2024-code-zap#898]
## 📌 어떤 기능을 리팩터링 하나요?
> AWS 서버를 코드잽 계정으로 마이그레이션한다.

## ⏳ 예상 소요 시간 (예상 해결 날짜)
> 이슈를 완료하기까지 예상되는 소요 시간을 시간 or 일 단위로 작성해주세요.

0일 0시간 소요 (00/00 00:00)

**Comment by kyum-q** [comment]
#944 로 이슈 변경
