### ISSUE TITLE
[REFACTOR] 콘솔 로그 하이라이팅

### ISSUE THREAD

**Issue by HoeSeong123** [woowacourse-teams/2024-code-zap#913]
## 📌 어떤 기능을 리팩터링 하나요?
> 콘솔 로그에는 하이라이팅을 추가합니다.

## AS-IS
- 그라파나에서 로그 라벨링을 진행하기 위해 하이라이팅을 제거했습니다.

## TO-BE
- 콘솔 로그는 그라파나에서 사용되지 않고, 로컬 환경에서 확인하기 불편하기 때문에 하이라이팅을 추가합

## ⏳ 예상 소요 시간 (예상 해결 날짜)
> 5분

**Comment by zeus6768** [comment]
로컬에서 console appender가 중복으로 등록되어 있던데, 개발 환경과 운영 환경처럼 Root 레벨로 하나만 등록하는 건 어떤가요?
