### ISSUE TITLE
[REFACTOR] Text 컴포넌트 자동줄바꿈 비활성화

### ISSUE THREAD

**Issue by vi-wolhwa** [woowacourse-teams/2024-code-zap#95]
## 📌 어떤 기능을 리팩터링 하나요?
Text 컴포넌트의 텍스트가 자동으로 줄이 변경되는 문제

## AS-IS
현재 `Hedaer`의 `New Template` 버튼의 텍스트가 줄바꿈 된다.

## TO-BE
텍스트의 길이에 따라 `New Template` 버튼의 길이를 조정한다.

## ⏳ 예상 소요 시간
.

## 🔍 참고할만한 자료
![image](https://github.com/user-attachments/assets/8f3aad69-1d67-4203-9e6f-a13b94ceb90c)
![image](https://github.com/user-attachments/assets/79f0bd53-59aa-428c-977b-633d83bfa870)

**Comment by kyum-q** [comment]
구현 료
