### ISSUE TITLE
[REFACTOR] 최근순과 오래된 순의 기준을 CreatedAt으로 변경

### ISSUE THREAD

**Issue by Hain-tain** [woowacourse-teams/2024-code-zap#959]
## 📌 어떤 기능을 리팩터링 하나요?

최근순 정렬 기준을 CreatedAt으로 변경합니다.

## AS-IS
- ModifiedAt을 기준으로 정렬

## TO-BE
- CreatedAt을 기준으로 정렬

## ⏳ 예상 소요 시간 (예상 해결 날짜)

2시간 소요 (00/00 00:00)

**Comment by Hain-tain** [comment]
## 1안(👍) : 
- 현재 최근순을 CreatedAt으로만 바꾸자! 
  - 이렇게되면 정렬조건은 여전히 3개로 유지됩니다. (최근순, 오래된 순, 좋아요 순)
  - 최근순과 오래된 순의 기준은 CreatedAt가 됩니다.

## 2안(😄)
- 최근 생성순과 최근 수정순으로 나누자!
  - 이렇게되면 정렬 조건은 4개가 됩니다.(최근 생성순, 최근 수정순, 오래된 순, 좋아요 순)
  - 이때 오래된 순은 CreatedAt을 기준으로합니다.

---

## 🎸 기타 
- 정렬조건을 CreatedAt 으로 바꾸더라도 좋아요를 눌렀을 때 수정 시간이 변경되면 안될 것 같습니다. 왜냐하면 현재 템플릿 상세페이지에서는 수정 시간과 생성시간을 모두 보여주고 있는데, 누군가가 좋아요를 눌렀다고 하여 내 탬플릿의 수정시간이 업데이트되는 것을 막아야 하기 때문입니다.
- 켬미가 예전에 작업했던 거 다시 부활...? 😂

**Comment by Jaymyong66** [comment]
저는 여력만 된다면 2안으로 선택지를 주는게 좋아보이긴 해요!

**Comment by kyum-q** [comment]
수정 시간이 템플릿 조회 시 보인다면 1,2안 중 무엇을 하든 좋아요로 인한 업데이트는 안되도록 수정해야겠네요.

그리고 2안을 카테고리나 공개 범위를 변경했을 때도 수정 시간이 업데이트 되는 현재의 형식을 가져간다면 좋습니다! 하지만 공개 범위나 카테고리를 변경했을 때 수정 시간이 업데이트 안되고 싶다면 코드 복잡성이 너무 증가해서 반대합니다..!

**Comment by Hain-tain** [comment]
투표 결과 1안과 2안의 찬성 비율이 동일하고, 1,2안에 들어가는 리소스 차이가 나지 않기 때문에 2안으로 구현하였습니다!

---
켬미의 말대로 2안으로 가더라도 수정 시간이 업데이트 되는 현재의 형식을 가져갈 예정입니다. 다만 좋아요를 눌렀을 때 수정시간이 변경되는 것은 버그라고 생각하기 때문에 그 부분만 수정되면 될 것 같습니다!

**Comment by zeus6768** [comment]
<img width="352" alt="Screenshot 2024-12-12 at 10 12 51 PM" src="https://github.com/user-attachments/assets/8bbca0ae-afec-4ae5-8145-832c8d52bd57" />

> 투표 결과 1안과 2안의 찬성 비율이 동일하고, 1,2안에 들어가는 리소스 차이가 나지 않기 때문에 2안으로 구현하였습니다!

투표 결과가 동일하지 않게 된 것 같은데,,, 혹시 다시 얘기를 할 필요는 없을까요?
